### ISSUE TITLE
[Bug]: Broken urls on Chainlink Keepers Architecture page

### ISSUE THREAD

**Issue by oldsku11** [smartcontractkit/documentation#810] opened 2022-06-16 14:50 UTC
### Describe the bug

2 urls are broken on [Chainlink Keepers Architecture](https://documentation-git-release-150-chainlinklabs.vercel.app/docs/chainlink-keepers/overview) page and lead to 404 page.

### To Reproduce

Case1:
1. Go to 'https://documentation-git-release-150-chainlinklabs.vercel.app/docs/chainlink-keepers/overview'
2. Click on 'Keepers-compatible' from _"Upkeeps: These are the maintenance tasks that smart contracts need external entities to service for them. These tasks are just functions on a smart contract and these contracts should be Keepers-compatible."_ text block
3. See error: Page Not Found (404)

Case2:
1. Go to 'https://documentation-git-release-150-chainlinklabs.vercel.app/docs/chainlink-keepers/overview'
2. Click on 'Keepers-compatible Contracts' from _"There are several contracts to be aware of. You can find them in the Chainlink repository. For details on how to use them see the Keepers-compatible Contracts page."_ text block
3. See error: Page Not Found (404)

### URLs

https://documentation-git-release-150-chainlinklabs.vercel.app/docs/chainlink-keepers/overview

### Expected behavior

redirects to [Making Keepers-compatible Contracts](https://documentation-git-release-150-chainlinklabs.vercel.app/docs/chainlink-keepers/compatible-contracts/) page

**Comment by oldsku11** [comment] 2022-06-16 14:51
Hi there!
my PR is ready. Can i submit it?

**Comment by aelmanaa** [comment] 2022-06-16 15:35
hi @oldsku11 

first of all, thanks so much for helping us. 

- case 1: not able to reproduce here https://docs.chain.link
   -  https://docs.chain.link/docs/chainlink-keepers/overview/#overview 
   - I click on [Keppers-compatible](https://docs.chain.link/docs/chainlink-keepers/compatible-contracts/)
   - works fine
- case2: same remark

why are you checking https://documentation-git-release-150-chainlinklabs.vercel.app/docs/chainlink-keepers/overview ? the prod URL is https://docs.chain.link. 

The former URL is linked to this [PR](https://github.com/smartcontractkit/documentation/pull/789) which will be fixed before merging it with main

**Comment by aelmanaa** [comment] 2022-06-16 15:45
@oldsku11 can this issue be closed?

**Closed** 2022-06-16 17:43 UTC
Labels: bug, question
